### ISSUE TITLE
Option to scan barcodes

### ISSUE THREAD

**Issue by teolemon** [rufuspollock-okfn/opd-product-browser-android#7]

**Comment by PhilippePlagnol** [comment]
You mean to use the camera to scan a barrecode and get the GTIN code ?

**Comment by teolemon** [comment]
yup

**Comment by PhilippePlagnol** [comment]
We could use an open source project called Zwing (https://code.google.com/p/zxing/) but I don't know it it's still alive because the last release is May 2013

Or other solutions like Scandit (http://www.scandit.com/), the barcode scanner is free and this tool seams to work very easily,...

other ideas ?

**Comment by tfmorris** [comment]
The sounds like a very basic, fundamental requirement and it doesn't sound hard to implement:

http://stackoverflow.com/questions/2050263/using-zxing-to-create-an-android-barcode-scanning-app

**Comment by PhilippePlagnol** [comment]
Yes indeed, it "seams" to be easy but I'm a noob in java and android so I have to see how to do 
or maybe a very good android developer ;) :p

**Comment by PhilippePlagnol** [comment]
Zxing has been added 
thank you to Darren Gudmundson and Nicolas Pieuchot
